instance_type	    	=	"t2.medium"
key_name	        	=	"terraform"
ami			            =	"ami-02eac2c0129f6376b"    #Use Centos7  image
vpc_id		        	=	"vpc-3b472741" #Default VPC ID 
user		        	=	"centos"
ssh_key_location    	=	"~/.ssh/id_rsa"        #Import private key pair to aws as "terraform"
zone_id			        =	"Z6XWWD56QDJWX"	   #Add hosted DNS zone ID here
domain			        =	"csamatov.net"
region 			        = 	"us-east-1"
